### PR TITLE
Fix NIST FIPS identifiers with months parsed wrongly

### LINKED ISSUE #72: (URGENT) NIST FIPS identifiers with months parsed wrongly
Changed? | PubID | Original | Changed? | MR | DOI
-- | -- | -- | -- | -- | --
TRUE | NBS FIPS PUB 107-FE | NBS FIPS 107-Feb1985 | TRUE | NBS.FIPS.PUB.107-FE | NBS.FIPS.107-Feb1985
TRUE | NBS FIPS PUB 107-MAr1985 | NBS FIPS 107-Mar1985 | TRUE | NBS.FIPS.PUB.107-MAr1985 | NBS.FIPS.107-Mar1985
TRUE | NBS FIPS PUB 108 | NBS FIPS 108 | TRUE | NBS.FIPS.PUB.108 | NBS.FIPS.108
TRUE | NBS FIPS PUB 108-1984 | NBS FIPS 108-1984 | TRUE | NBS.FIPS.PUB.108-1984 | NBS.FIPS.108-1984
TRUE | NBS FIPS PUB 109 | NBS FIPS 109 | TRUE | NBS.FIPS.PUB.109 | NBS.FIPS.109
TRUE | NBS FIPS PUB 109-1985 | NBS FIPS 109-1985 | TRUE | NBS.FIPS.PUB.109-1985 | NBS.FIPS.109-1985
TRUE | NBS FIPS PUB 110 | NBS FIPS 110 | TRUE | NBS.FIPS.PUB.110 | NBS.FIPS.110
TRUE | NBS FIPS PUB 111 | NBS FIPS 111 | TRUE | NBS.FIPS.PUB.111 | NBS.FIPS.111
TRUE | NBS FIPS PUB 111-1985 | NBS FIPS 111-1985 | TRUE | NBS.FIPS.PUB.111-1985 | NBS.FIPS.111-1985
TRUE | NBS FIPS PUB 11-1eSep1977 | NBS FIPS 11-1-Sep1977 | TRUE | NBS.FIPS.PUB.11-1eSep1977 | NBS.FIPS.11-1-Sep1977
TRUE | NBS FIPS PUB 11-1eSep30 | NBS FIPS 11-1-Sep30 | TRUE | NBS.FIPS.PUB.11-1eSep30 | NBS.FIPS.11-1-Sep30/1977
TRUE | NBS FIPS PUB 112 | NBS FIPS 112 | TRUE | NBS.FIPS.PUB.112 | NBS.FIPS.112
TRUE | NBS FIPS PUB 113 | NBS FIPS 113 | TRUE | NBS.FIPS.PUB.113 | NBS.FIPS.113
TRUE | NBS FIPS PUB 114-DE | NBS FIPS 114-Dec1985 | TRUE | NBS.FIPS.PUB.114-DE | NBS.FIPS.114-Dec1985
TRUE | NBS FIPS PUB 114-SE | NBS FIPS 114-Sep1985 | TRUE | NBS.FIPS.PUB.114-SE | NBS.FIPS.114-Sep1985
TRUE | NBS FIPS PUB 115-MAr1985 | NBS FIPS 115-Mar1985 | TRUE | NBS.FIPS.PUB.115-MAr1985 | NBS.FIPS.115-Mar1985
TRUE | NBS FIPS PUB 115-SE | NBS FIPS 115-Sep1985 | TRUE | NBS.FIPS.PUB.115-SE | NBS.FIPS.115-Sep1985
TRUE | NBS FIPS PUB 116-A | NBS FIPS 116-Apr1985 | TRUE | NBS.FIPS.PUB.116-A | NBS.FIPS.116-Apr1985
TRUE | NBS FIPS PUB 116-SE | NBS FIPS 116-Sep1985 | TRUE | NBS.FIPS.PUB.116-SE | NBS.FIPS.116-Sep1985

### PR DESCRIPTION
**Pull request by mico**
closes #72

### CODE REVIEW

File: spec/nist_pubid/document_spec.rb [hunk 1]
```diff
@@ -700,6 +706,34 @@
       it_behaves_like "converts pubid to different formats"
     end
 
+    context "NBS FIPS 107-Mar1985" do
+      let(:original_pubid) { "NBS FIPS 107-Mar1985" }
```
Comment (ronaldtse) [inline spec/nist_pubid/document_spec.rb:710]: Can we fully parse the dates, i.e. "Mar1985" into `year: 1985, month: 03` in the PubID object?

**Review by ronaldtse — CHANGES_REQUESTED** [review]

File: spec/nist_pubid/document_spec.rb (hunk 1 above)
Comment (mico) [reply spec/nist_pubid/document_spec.rb:710]: > Can we fully parse the dates, i.e. "Mar1985" into `year: 1985, month: 03` in the PubID object?

Sometimes the second number is not edition (NIST SP 800-53r5).
If it's parsable date, like "NIST TN 1297-1993" then we put it to edition, but "NIST FIPS 140-3" is it edition here?
I mean sometimes edition is not a date, how we can recognize if it's edition or sequence number or volume or something else?

Comment (ronaldtse) [reply spec/nist_pubid/document_spec.rb:710]: We definitely need a pattern for "date" i.e. `\w{3,4}\d{4}`. A simplistic approach will not work.

**Comment by mico** [comment]
closes #73

**Comment by mico** [comment]
@ronaldtse I'm parsing dates in editions now, but now I facing with the problem I mentioned before and don't have idea yet how to deal with that. You can see tests are failing now, because:
```
expected: "NIST SP 800-53r5"
     got: "NIST SP 800r5e53"
```

How can I know "53" in "NIST SP 800-53r5" is not an edition, but part of report sequence?
For example "NIST HB 135-2020" - here it's an edition, and "3" here "NIST FIPS 140-3" is also edition?

**Comment by ronaldtse** [comment]
@mico we will have to split parsing by series.
* In "SP {800-NNN}", "800-NNN" is always the report number.
* In "HB NNN-XXXX", "NNN" is always the report number.

**Comment by mico** [comment]
@ronaldtse could you check if everything looks good?
In most cases it's still not clear to me if sequence should be edition or not. Opening pdfs is not helping, can't find information if it's edition or not.

**Comment by ronaldtse** [comment]
> In most cases it's still not clear to me if sequence should be edition or not. Opening pdfs is not helping, can't find information if it's edition or not.

@mico Can you clarify which ones are unclear? It's hard to answer without knowing the exact instances.

File: spec/nist_pubid/document_spec.rb [hunk 2]
```diff
@@ -549,7 +541,8 @@
     end
 
     context "NBS IR 80-2073.3" do
-      let(:short_pubid) { "NBS IR 80-2073.3" }
+      let(:original_pubid) { "NBS IR 80-2073.3" }
+      let(:short_pubid) { "NBS IR 80e2073.3" }
```
Comment (ronaldtse) [inline spec/nist_pubid/document_spec.rb:545]: This is really "NBS IR 80-2073.3". Can we not change the ones that are correct right now?

Screenshot 2022-01-14 at 5 04 23 PM

File: spec/nist_pubid/document_spec.rb [hunk 3]
```diff
@@ -631,7 +630,8 @@
     end
 
     context "NIST GCR 17-917-45" do
-      let(:short_pubid) { "NIST GCR 17-917-45" }
+      let(:original_pubid) { "NIST GCR 17-917-45" }
+      let(:short_pubid) { "NIST GCR 17-917e45" }
```
Comment (ronaldtse) [inline spec/nist_pubid/document_spec.rb:634]: As mentioned in https://github.com/metanorma/nist-pubid/pull/57#issuecomment-1008968740, which was already fixed, the GCR reports use a 2 part or 3 part number. Please revert this.

**Comment by ronaldtse** [comment]
I can see there are some challenges and misunderstandings here. Regular expressions don't seem to be expressive enough to serve this purpose. We need to parse the identifier like an **onion**. Maybe try using the Parslet gem to develop and parse a grammar. Without grammar the resulting parsing will be fragile.
https://github.com/kschiess/parslet

1. The report number schema for each series can be **different**. Therefore the meaning of "-" is different. GCR takes a 2-part or 3-part number. In "SP 800-(N+){part}", the "800-(N+){part}" is always the report number, and anything after is an edition.

2. Every series should probably be a Ruby Class (we can have a generic series for simple ones) for serialisation purposes.

**Comment by mico** [comment]
> 1. The report number schema for each series can be **different**. Therefore the meaning of "-" is different. GCR takes a 2-part or 3-part number. In "SP 800-(N+){part}", the "800-(N+){part}" is always the report number, and anything after is an edition.
> 2. Every series should probably be a Ruby Class (we can have a generic series for simple ones) for serialisation purposes.

How can I get schema for each series? By looking at pdf sometimes I can't understand is it edition or not.

**Comment by ronaldtse** [comment]
> How can I get schema for each series? By looking at pdf sometimes I can't understand is it edition or not.

We will have to find out the schema per series and document them.

**Comment by mico** [comment]
> I can see there are some challenges and misunderstandings here. Regular expressions don't seem to be expressive enough to serve this purpose. We need to parse the identifier like an **onion**. Maybe try using the Parslet gem to develop and parse a grammar. Without grammar the resulting parsing will be fragile.
> 
> https://github.com/kschiess/parslet

How soon you want to implement parsing with parslet? It is not for this pull request, right?

**Comment by ronaldtse** [comment]
We don’t need to use parslet right away but it will be challenging to wrestle regular expressions. I suggest we could first have series-specific regexes which will help. We need a per series schema.

File: regexps.yaml [hunk 4]
```diff
@@ -0,0 +1,17 @@
+edition:
```
Comment (ronaldtse) [inline regexps.yaml:1]: Instead of `regexps.yaml` (keeping multiple series in 1 file), can we have different series classes (keeping edition, code regexes in every series class). For series that do not need special parsing, we can use a generic class to represent. Thanks!

**Review by ronaldtse — CHANGES_REQUESTED** [review]

**Comment by mico** [comment]
last commit related to #32

**Review by ronaldtse — APPROVED** [review]
